### ISSUE TITLE
TensorFlow Model Codes and OOP

### ISSUE THREAD

**Issue by hunkim** [wookayin/TensorFlowKR-2017-talk-bestpractice#3]
Very nice slides! I really appreciate it.

Do you know where can I find the original link of "TensorFlow Model Codes and OOP" in your slide 10?

![image](https://cloud.githubusercontent.com/assets/901975/23093919/326afb72-f62a-11e6-8ace-d980b33e0ca4.png)

**Comment by wookayin** [comment]
Hi, thanks for your comment. The link points to one of my private note, and it is somewhat difficult to publicize it at this point. However, the core messages from the note are covered in the rest of slides. I also would like to share the article with everyone after I make it polished. Thank you!

**Comment by hunkim** [comment]
Thanks! I thought it is an article on Internet.
